=== TymofiiPys/OOP-LabsAndTasks/OOP-Lab2-Pysarenkov/candy.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="CandyList">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Candy" type="CandyType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="CandyType">
        <xs:all>
            <xs:element name="Name" type="nonEmptyString"/>
            <xs:element name="Energy" type="xs:positiveInteger"/>
            <xs:element name="Ingredients" type="IngredientsType"/>
            <xs:element name="Value" type="ValueType"/>
            <xs:element name="Production" type="nonEmptyString"/>
        </xs:all>
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="Type" type="candyType" use="required"/>
    </xs:complexType>

    <xs:complexType name="IngredientsType">
        <xs:all>
            <xs:element name="water" type="percentage"/>
            <xs:element name="sugar" type="nonNegativeDouble"/>
            <xs:element name="fructose" type="nonNegativeDouble"/>
            <xs:element name="choc_type" type="chocType"/>
            <xs:element name="vanillin" type="nonNegativeDouble"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="ValueType">
        <xs:all>
            <xs:element name="protein" type="nonNegativeDouble"/>
            <xs:element name="fat" type="nonNegativeDouble"/>
            <xs:element name="carbohydrates" type="nonNegativeDouble"/>
        </xs:all>
    </xs:complexType>

    <xs:simpleType name="nonEmptyString">
        <xs:restriction base="xs:string">
            <xs:pattern value=".+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="nonNegativeDouble">
        <xs:restriction base="xs:double">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="candyType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Шоколадна"/>
            <xs:enumeration value="Карамель"/>
            <xs:enumeration value="Ірис"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="chocType">
        <xs:restriction base="xs:string">
            <xs:pattern value="(.*шоколад)|( )"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="percentage">
        <xs:restriction base="xs:double">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="100"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== TymofiiPys/OOP-LabsAndTasks/OOP-Lab2-Pysarenkov/candylist.xml
<?xml version="1.0" encoding="WINDOWS-1251"?>
<CandyList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="candy.xsd">
    <Candy id="ID-1" Type="Шоколадна">
        <Name>Смакулька</Name>
        <Energy>150</Energy>
        <Ingredients>
            <water>10.5</water>
            <sugar>25.0</sugar>
            <fructose>15.2</fructose>
            <choc_type>Молочний шоколад</choc_type>
            <vanillin>2.0</vanillin>
        </Ingredients>
        <Value>
            <protein>2.5</protein>
            <fat>8.0</fat>
            <carbohydrates>30.5</carbohydrates>
        </Value>
        <Production>СмакульКО</Production>
    </Candy>
    <Candy id="ID-2" Type="Шоколадна">
        <Name>НоваШоколада</Name>
        <Energy>120</Energy>
        <Ingredients>
            <water>12.0</water>
            <sugar>22.5</sugar>
            <fructose>20.0</fructose>
            <choc_type>Темний шоколад</choc_type>
            <vanillin>1.5</vanillin>
        </Ingredients>
        <Value>
            <protein>1.8</protein>
            <fat>5.0</fat>
            <carbohydrates>28.0</carbohydrates>
        </Value>
        <Production>НоваКом</Production>
    </Candy>
    <Candy id="ID-3" Type="Карамель">
        <Name>КарамельХруст</Name>
        <Energy>180</Energy>
        <Ingredients>
            <water>8.0</water>
            <sugar>30.0</sugar>
            <fructose>18.0</fructose>
            <choc_type> </choc_type>
            <vanillin>2.5</vanillin>
        </Ingredients>
        <Value>
            <protein>3.0</protein>
            <fat>10.0</fat>
            <carbohydrates>35.0</carbohydrates>
        </Value>
        <Production>НямНямІнк</Production>
    </Candy>
    <Candy id="ID-4" Type="Ірис">
        <Name>IRISка</Name>
        <Energy>130</Energy>
        <Ingredients>
            <water>11.0</water>
            <sugar>20.0</sugar>
            <fructose>25.0</fructose>
            <choc_type> </choc_type>
            <vanillin>1.0</vanillin>
        </Ingredients>
        <Value>
            <protein>2.2</protein>
            <fat>5.5</fat>
            <carbohydrates>30.0</carbohydrates>
        </Value>
        <Production>ШОКОЛАДМАСТЕРС</Production>
    </Candy>
    <Candy id="ID-5" Type="Карамель">
        <Name>Карамеееееееееееееее</Name>
        <Energy>140</Energy>
        <Ingredients>
            <water>10.0</water>
            <sugar>25.5</sugar>
            <fructose>15.0</fructose>
            <choc_type> </choc_type>
            <vanillin>1.8</vanillin>
        </Ingredients>
        <Value>
            <protein>2.0</protein>
            <fat>6.0</fat>
            <carbohydrates>32.0</carbohydrates>
        </Value>
        <Production>ЕЕЕЕЕЕ КО</Production>
    </Candy>
</CandyList>

=== TymofiiPys/OOP-LabsAndTasks/OOP-Lab2-Pysarenkov/candylist_test.xml
<?xml version="1.0" encoding="WINDOWS-1251"?>
<CandyList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="candy.xsd">
    <Candy id="ID-1" Type="Шоколадна">
        <Name>Смакулька</Name>
        <Energy>150</Energy>
        <Ingredients>
            <water>10.5</water>
            <sugar>25.0</sugar>
            <fructose>15.2</fructose>
            <choc_type>Молочний шоколад</choc_type>
            <vanillin>2.0</vanillin>
        </Ingredients>
        <Value>
            <protein>2.5</protein>
            <fat>8.0</fat>
            <carbohydrates>30.5</carbohydrates>
        </Value>
        <Production>СмакульКО</Production>
    </Candy>
    <Candy id="ID-2" Type="Шоколадна">
        <Name>НоваШоколада</Name>
        <Energy>120</Energy>
        <Ingredients>
            <water>12.0</water>
            <sugar>22.5</sugar>
            <fructose>20.0</fructose>
            <choc_type>Темний шоколад</choc_type>
            <vanillin>1.5</vanillin>
        </Ingredients>
        <Value>
            <protein>1.8</protein>
            <fat>5.0</fat>
            <carbohydrates>28.0</carbohydrates>
        </Value>
        <Production>НоваКом</Production>
    </Candy>
</CandyList>
